export const ERROR_CODES = {
  INV_STOCK_INSUFFICIENT: 'INV_STOCK_INSUFFICIENT',
  INV_CUSTOMER_REQUIRED: 'INV_CUSTOMER_REQUIRED',
  INV_SUPPLIER_REQUIRED: 'INV_SUPPLIER_REQUIRED',
  INV_ITEMS_REQUIRED: 'INV_ITEMS_REQUIRED',
  INV_PAYMENT_ACCOUNT_REQUIRED: 'INV_PAYMENT_ACCOUNT_REQUIRED',
  INV_PAYMENT_ACCOUNT_FOR_CREDIT_NOT_ALLOWED:
    'INV_PAYMENT_ACCOUNT_FOR_CREDIT_NOT_ALLOWED',
  INV_ITEM_NOT_FOUND: 'INV_ITEM_NOT_FOUND',
  INV_NOT_FOUND: 'INV_NOT_FOUND',
  INV_SAFE_BALANCE_INSUFFICIENT: 'INV_SAFE_BALANCE_INSUFFICIENT',
  QUOTATION_ITEMS_REQUIRED: 'QUOTATION_ITEMS_REQUIRED',
  QUOTATION_TOTALS_REQUIRED: 'QUOTATION_TOTALS_REQUIRED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
